Implement .doas.config installation logic

diff --git a/.bin/openbsd/doas b/.bin/openbsd/doas
--- a/.bin/openbsd/doas
+++ b/.bin/openbsd/doas
@@ -4,8 +4,43 @@
 # A wrapper for doas(1)
 #
 
-# Locate true path of doas executable
+# Set true path of doas executable
 DOAS="/usr/bin/doas"
 
-exec "$DOAS"
+# Set path of target config
+CONFIG="/etc/doas.conf"
+
+# Set path os source config
+SOURCE="${HOME}/.doas.config"
+
+# Validate hardcoded executable path
+if [ ! -x "$DOAS" ]
+then
+	echo "Error: '${DOAS}' not found" 1>&2
+	exit 1
+fi
+
+if [ ! -f "$CONFIG" ]
+then
+	echo "Error: '${CONFIG}' not found" 1>&2
+	exit 1
+fi
+
+# Check that installation would work
+if [ "$("$DOAS" -C "$CONFIG" cp -f "$SOURCE" "$CONFIG")" = "deny" ]
+then
+	echo "Error: Cannot install '${SOURCE}'" 1>&2
+	exit 1
+fi
+
+# Validate new config
+if "$DOAS" -C "$SOURCE"
+then
+	"$DOAS" cp -f "$SOURCE" "$CONFIG"
+else
+	echo "Error: "  1>&2
+	exit 1
+fi
+
+exec "$DOAS" $@
 
